### ISSUE TITLE
Ignoring index 0 in the sites array

### ISSUE THREAD

**Issue by rogeriopvl** [nikcub/Force-SSL#1]
Hi!

According to [line 25 in content.js](http://github.com/nikcub/Force-SSL/blob/master/chrome/src/content.js#L25), the code is always ignoring the first element in the sites array.

Although this might not be a real issue because I believe that `facebook.com` always redirects to `www.facebook.com`, but in long term if the sites array gets changed, it might be left behind forgotten.

Cheers!

**Comment by nikcub** [comment]
Hey - I completely changed the code, and it has a new name now. Checkout /nikcub/Fidelio/ - I don't think this issue applies in the new base, but feel free to check it out and let me know if it does.
